# Generated by Django 3.2.14 on 2022-07-25 03:46

import AFWeb.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vi_tri', models.CharField(db_index=True, default='default', max_length=150, verbose_name='Vị trí')),
                ('size', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(db_index=True, max_length=150, verbose_name='Chuyên mục')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200, unique=True, verbose_name='Tiêu đề')),
                ('trich_yeu', models.CharField(blank=True, max_length=500, null=True, verbose_name='Trích yếu')),
                ('noi_dung', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Nội dung')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày đăng')),
                ('hinh_anh', models.FileField(default='', null=True, upload_to=AFWeb.models.TinTuc.news_avartar_image_directory_path, verbose_name='Hình ảnh')),
                ('tin_noi_bat', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('duyet', models.BooleanField(default=True, verbose_name='Duyệt')),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('the_loai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AFWeb.theloai')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(default='', null=True, upload_to='uploads/imgs/%Y/%m/%d/')),
                ('gallery_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AFWeb.galleryactivity')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chu_de', models.CharField(max_length=200, unique=True, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('noi_dung', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Nội dung')),
                ('lien_ket', models.CharField(blank=True, default='#', max_length=200, null=True, verbose_name='Liên kết')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ngày đăng')),
                ('hinh_anh', models.FileField(default='', null=True, upload_to=AFWeb.models.Banner.banner_directory_path, verbose_name='Hình ảnh')),
                ('slide', models.BooleanField(default=False, verbose_name='slide')),
                ('duyet', models.BooleanField(default=True, verbose_name='Duyệt')),
                ('banner_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AFWeb.bannerloc')),
            ],
        ),
    ]
